apiVersion: v1
kind: Secret
metadata:
  name: cloud-provider-config
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- if .Values.vsphereWithKubernetes }}
  cloudprovider.conf: {{ b64enc "nothing" }}
{{- else }}
  cloudprovider.conf: {{ include "cloud-provider-config" . | b64enc }}
{{- end }}