---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "csi-driver-node.extensionsGroup" . }}:{{ include "csi-driver-node.name" . }}:csi-driver
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["volumeattachments"]
  verbs: ["get", "list", "watch", "update", "patch"]
{{- if not .Values.pspDisabled }}
- apiGroups: ["policy", "extensions"]
  resourceNames: ["{{ include "csi-driver-node.extensionsGroup" . }}.{{ include "csi-driver-node.name" . }}.csi-driver-node"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
{{- end }}
- apiGroups: ["cns.vmware.com"]
  resources: ["cnsvolumeinfos"]
  verbs: ["create", "get", "list", "watch", "delete"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "get", "list", "update", "delete","patch"]
- apiGroups: [ "cns.vmware.com" ]
  resources: [ "csinodetopologies"]
  verbs: ["get", "update", "watch", "list", "patch"]
- apiGroups: ["cns.vmware.com"]
  resources: ["cnsvolumeoperationrequests"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["csinodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [ "snapshot.storage.k8s.io" ]
  resources: [ "volumesnapshotcontents" ]
  verbs: ["get", "list", "watch"]
